 CREATE TABLE 'temperatures'.'Room' 
 ( 'Id' INT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
 'Name' VARCHAR(100) NULL 
 )

CREATE TABLE 'temperatures'.'Reading'
( 'Id' INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
'RoomId' INT NOT NULL , 
'Temperature' DECIMAL(6, 2) NOT NULL,
'Date' DATETIME NOT NULL,
FOREIGN KEY(RoomId) REFERENCES Room(Id) ON DELETE CASCADE
)